## ?????????????????????????????????????????????
## BASE DE DATOS
## ?????????????????????????????????????????????

## DESARROLLO (activo)
##spring.datasource.url=jdbc:postgresql://localhost:5432/prueba_db
##spring.datasource.username=postgres
##spring.datasource.password=Sandoval64
##spring.datasource.driver-class-name=org.postgresql.Driver

## PRODUCCIÓN - Render + NeonDB (comentar las de arriba y descomentar estas)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

## ?????????????????????????????????????????????
## JPA / HIBERNATE
## ?????????????????????????????????????????????
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## DESARROLLO: conserva datos y agrega columnas nuevas automáticamente
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true

## PRODUCCIÓN (comentar las dos de arriba y descomentar estas)
## Primer deploy: usar "update" para que Hibernate cree las tablas
## Después del primer deploy: cambiar a "none"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

## ?????????????????????????????????????????????
## SERVIDOR
## ?????????????????????????????????????????????
server.tomcat.threads.max=200
server.tomcat.connection-timeout=5s
server.max-http-request-header-size=2MB
server.tomcat.max-swallow-size=2MB
server.tomcat.max-http-post-size=2MB

## ?????????????????????????????????????????????
## JWT
## ?????????????????????????????????????????????
##jwt.secret=QVJRVUlURUNUVVJBX0FQTElDQUNJT05FU19XRUJfVVBDX0lOR0VOSUVSSUFfU0lTVEVNQVNfREVfSU5GT1JNQUNJT04K
##jwt.expiration=10800000

## PRODUCCIÓN (comentar las dos de arriba y descomentar estas)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
